//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("NCmdLiner.Tests features NCmdLiner tests.")]
[assembly: System.Reflection.AssemblyCompany("github.com/trondr")]
[assembly: System.Reflection.AssemblyProduct("NCmdLiner.Tests")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © <github.com/trondr> 2017")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2.17086.227.6e00900")]
[assembly: System.Reflection.AssemblyVersion("1.2.17086.227")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.17086.227")]


