//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("NCmdLiner.Tests features NCmdLiner tests.")]
[assembly: System.Reflection.AssemblyCompany("github.com/trondr")]
[assembly: System.Reflection.AssemblyProduct("NCmdLiner.Tests")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © github.com/trondr 2013-2018")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.18077.333.22abbaf")]
[assembly: System.Reflection.AssemblyVersion("2.0.18077.333")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.18077.333")]


