//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("NCmdLiner is a self documenting command line parser")]
[assembly: AssemblyCompany("github.com/trondr")]
[assembly: AssemblyProduct("NCmdLiner")]
[assembly: AssemblyCopyright("Copyright © <github.com/trondr> 2013")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("1.0.13302.59d4123")]
[assembly: AssemblyVersion("1.0.13302.106")]
[assembly: AssemblyFileVersion("1.0.13302.106")]


